ARG APISIX_VERSION="3.2.1"
FROM apache/apisix:$APISIX_VERSION-centos

# in github action, change the source of yum is not ok
# note: uncomment below if it's slow to build image
# RUN mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && \
#     curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.cloud.tencent.com/repo/centos7_base.repo && \
#     yum clean all

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN cat /etc/yum.repos.d/CentOS-Base.repo

RUN yum clean all && yum update -y

RUN yum install -y sudo make gcc curl wget unzip git valgrind

ARG APISIX_VERSION
RUN curl https://raw.githubusercontent.com/apache/apisix/${APISIX_VERSION}/utils/linux-install-luarocks.sh | bash
# lock the version of luasystem, otherwise the busted won't be installed success
RUN luarocks install https://luarocks.org/manifests/lunarmodules/luasystem-0.2.1-0.rockspec
RUN luarocks install https://github.com/lunarmodules/busted/releases/download/v2.1.1/busted-2.1.1-1.rockspec

COPY ci/requirements-dev-0.rockspec /
RUN luarocks install --deps-only /requirements-dev-0.rockspec --server https://luarocks.cn

ENV LUA_PATH='/usr/local/apisix/?.lua;/usr/local/apisix/?/init.lua;/usr/local/apisix/deps/share/lua/5.1/?/init.lua;/usr/local/apisix/deps/share/lua/5.1/?.lua;/usr/local/apisix/apisix/?.lua;/usr/local/apisix/t/?.lua;;'
ENV LUA_CPATH='/usr/local/apisix/?.so;/usr/local/apisix/deps/lib/lua/5.1/?.so;/usr/local/apisix/deps/lib64/lua/5.1/?.so;;'

# this change in 3.2.1 will make the `stub(ngx.req, "set_header")` not working, and the unittest will be failed
# RUN sed -i 's#req_set_header(header_name, header_value)#ngx.req.set_header(header_name, header_value)#g' /usr/local/apisix/apisix/core/request.lua

RUN mkdir -p /bkgateway/apisix/plugins /bkgateway/tests/ /bkgateway/logs/ /bkgateway/conf/
WORKDIR /bkgateway/
COPY ci/run-test-busted.sh /
CMD ["/run-test-busted.sh"]
