ARG APISIX_VERSION="3.13.0"
FROM apache/apisix:$APISIX_VERSION-redhat

RUN yum install -y sudo make gcc wget unzip git # valgrind


ARG APISIX_VERSION
RUN wget https://raw.githubusercontent.com/apache/apisix/${APISIX_VERSION}/utils/linux-install-luarocks.sh && bash linux-install-luarocks.sh

# lock the version of luasystem, otherwise the busted won't be installed success
RUN luarocks install https://luarocks.org/manifests/lunarmodules/luasystem-0.6.3-1.rockspec
RUN luarocks install https://github.com/lunarmodules/busted/releases/download/v2.2.0/busted-2.2.0-1.rockspec

COPY ci/requirements-dev-0.rockspec /
RUN luarocks install --deps-only /requirements-dev-0.rockspec --server https://luarocks.cn

ENV LUA_PATH='/usr/local/apisix/?.lua;/usr/local/apisix/?/init.lua;/usr/local/apisix/deps/share/lua/5.1/?/init.lua;/usr/local/apisix/deps/share/lua/5.1/?.lua;/usr/local/apisix/apisix/?.lua;/usr/local/apisix/t/?.lua;;'
ENV LUA_CPATH='/usr/local/apisix/?.so;/usr/local/apisix/deps/lib/lua/5.1/?.so;/usr/local/apisix/deps/lib64/lua/5.1/?.so;;'

# this change in 3.2.1 will make the `stub(ngx.req, "set_header")` not working, and the unittest will be failed
# RUN sed -i 's#req_set_header(header_name, header_value)#ngx.req.set_header(header_name, header_value)#g' /usr/local/apisix/apisix/core/request.lua

RUN mkdir -p /bkgateway/apisix/plugins /bkgateway/tests/ /bkgateway/logs/ /bkgateway/conf/
WORKDIR /bkgateway/
COPY ci/run-test-busted.sh /
CMD ["/run-test-busted.sh"]
