fail_fast: true
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: python
        entry: cd src/apisix && make lint RUN_WITH_IT=""
        files: src/apisix
  - repo: local
    hooks:
      - id: Name check
        name: Check sensitive info
        verbose: true
        language: system
        require_serial: true
        entry: bash -c "if [[ -d pre_commit_hooks ]]; then pre_commit_hooks/rtx.sh $@; fi"
      - id: IP check
        name: Check sensitive info
        verbose: true
        language: system
        require_serial: true
        entry: bash -c "if [[ -d pre_commit_hooks ]]; then pre_commit_hooks/ip.sh $@; fi"